@ECHO OFF

ECHO WARNING: DO NOT, ATTEMPT, TO EXECUTE PROJECT-BETA...
ECHO FILES ARE COTAMINATED WITH CODE THAT CRASHES PROJECT-BETA, LEAVING THE GAME UNPLAYABLE.
ECHO IF YOU CONTINUE, YOUR CLIENT WILL BE DELETED.
ECHO ARE YOU SURE YOU WANT TO CONTINUE?
pause